### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by pratap-panabaka** [michael-duke/Micro-Tasks#5]
Your project looks great!
the UI and UX are well done.

we noticed you have followed:
DRY, KISS and YAGNI concepts.

good job.

[Optional Suggestion}
It could be better if you go with pure CSS instead of Framework for CSS.

**Comment by michael-duke** [comment]
Thank you for the comments and feedback @PRATAP-KUMAR  @David-Kasilia and @itsmraga-hub 😄 Happy coding 🚀
